nginx:
  image: wonderfall/boring-nginx
  container_name: nginx
  links:
    - flarum:flarum
  ports:
    - 80:8000
  volumes:
    - ${PWD}/docker/nginx/sites-enabled:/sites-enabled
    - ${PWD}/docker/nginx/log:/var/log/nginx

flarum:
  image: mondedie/docker-flarum:0.1.0-beta.7.2-stable
  container_name: flarum
  links:
    - mariadb:mariadb
  environment:
    - DEBUG=true
    - FORUM_URL=http://flarum.local/
    - DB_PASS=277F9fqGEgyB
  volumes:
    - ${PWD}/docker/flarum/assets:/flarum/app/assets
    - ${PWD}/docker/flarum/extensions:/flarum/app/extensions

mariadb:
  image: mariadb:10.1
  container_name: mariadb
  ports:
    - 3306:3306
  volumes:
    - ${PWD}/docker/mysql/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=KthJ8k2DE4q3
    - MYSQL_DATABASE=flarum
    - MYSQL_USER=flarum
    - MYSQL_PASSWORD=277F9fqGEgyB
