#!/bin/sh

action=$1

case "$action" in
  "init"|"migrate"|"update-bundle"|"fluxbb-db-init"|"flarum-db-init")
    docker run --rm -i \
      --env-file $(pwd)/.env \
      --link mariadb:mariadb \
      -v $(pwd)/docker/flarum/assets:/flarum/app/assets \
      -v $(pwd)/scripts:/scripts migrator "$@"
    ;;
  "build")
    docker build -t migrator $(pwd)
    docker images | grep migrator
    ;;
  "remove")
    docker-compose -f $(pwd)/docker-compose.yml stop
    docker-compose -f $(pwd)/docker-compose.yml rm
    ;;
  "clean")
    docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi
	  docker volume ls -qf dangling=true | xargs -r docker volume rm
    ;;
  *)
    echo "Usage : $0 init|migrate|update-bundle|fluxbb-db-init|flarum-db-init|build|remove|clean"
    ;;
esac

exit 0
